#!/bin/bash

sudo grep "Color" /etc/pacman.conf && \
sudo sed -i -e 's/#Color/Color/g' /etc/pacman.conf && \
sudo grep "Color" /etc/pacman.conf || exit 1

sudo grep "\[multilib\]" /etc/pacman.conf && \
sudo sed -i -e 's/\#\[multilib\]/[multilib]\nInclude \= \/etc\/pacman.d\/mirrorlist/g' /etc/pacman.conf && \
sudo grep "\[multilib\]" /etc/pacman.conf || exit 1

sudo pacman -Syu || exit 1
