#!/bin/bash
sudo pacman -S --needed --noconfirm alacritty tmux rsync man konsole

ln -sfv ~/.dotfiles/configuration/alacritty ~/.config/
ln -sfv ~/.dotfiles/configuration/konsole ~/.local/share/
ln -sfv ~/.dotfiles/configuration/konsolerc ~/.config

source $DOTFILES/scripts/Shared/004_terminal
