#!/bin/bash
set -euxo pipefail
source "$DOTFILES/.bash_helpers"

require_variable INCLUDE_AUDIO

if [ $INCLUDE_AUDIO == 1 ]; then
    sudo pacman -S --needed --noconfirm pulseaudio pavucontrol playerctl alsa-utils \
         pulseaudio-alsa pulseaudio-bluetooth pulseaudio-equalizer pulseaudio-jack \
         pulseaudio-zeroconf vlc kmix

    if ! command -v spotify &> /dev/null
    then
        curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | gpg --import -
        yay -S --needed --noconfirm spotify
    else
        echo "spotify already installed"
    fi

    if ! command -v alsa-tray &> /dev/null
    then
        yay -S --needed --noconfirm alsa-tray
    else
        echo "alsa-tray already installed"
    fi
else
    echo "Audio installation skipped!"
fi
