#!/bin/bash

sudo pacman -S --needed --noconfirm neovim ruby xclip python2-pip
yay -S --needed --noconfirm elixir-ls

if ! command -v ag &> /dev/null
then
    yay -S --needed --noconfirm the_silver_searcher
else
    echo "the_silver_searcher already installed"
fi

sudo pacman -S --needed --noconfirm linux-headers gcc make python-pip nodejs npm php composer \
ctags elixir python-pylint python-pillow yarn

source $DOTFILES/scripts/Shared/005_neovim
