#!/bin/bash
set -euxo pipefail
source "$DOTFILES/.bash_helpers"

require_variable INCLUDE_SCREEN_CAPTURE

if [ $INCLUDE_SCREEN_CAPTURE == 1 ]; then

    sudo pacman -S --needed --noconfirm obs-studio peek deepin-screenshot

    if ! command -v deepin-screen-recorder &> /dev/null
    then
        yay -S --needed --noconfirm deepin-screenshot-copy-patch
    else
        echo "deepin-screen-recorder already installed"
    fi

    ln -sfv $DOTFILES/deepin ~/.config

    if [ ! -d ~/Screenshots ]; then
        mkdir ~/Screenshots
    fi

else
    echo "Screen capture tool installation skipped!"
    fi
