#!/bin/bash
set -euxo pipefail

if [ -z ${SSH_ENABLED+x} ]; then
        echo "SSH_ENABLED not set!"
        exit 1
fi

if [ ! -f $HOME/.ssh/id_rsa.pub ]; then
	echo "ssh key doesn' t exist, generating..."
	ssh-keygen -t rsa -b 4096
fi

sudo cp -v $DOTFILES/ssh/sshd_config /etc/ssh/sshd_config
sudo cp -v $DOTFILES/ssh/motd /etc/ssh/motd

if [ $SSH_ENABLED == 1 ]; then
        sudo systemctl enable sshd
        sudo systemctl restart sshd
else
        sudo systemctl disable sshd
fi
