#!/bin/bash
ln -sfv ~/.dotfiles/configuration/nvim ~/.config

# composer global require hirak/prestissimo # install things in parallel
composer global config minimum-stability dev
composer global require phpdocumentor/phpdocumentor
composer global require phpmd/phpmd
composer global require squizlabs/php_codesniffer
composer global require -W phpactor/phpactor

sudo npm install -g eslint lynt pug-lint-vue instant-markdown-d
sudo npm install -g npm
sudo npm install -g eslint
sudo npm install -g instant-markdown-d
sudo npm install -g neovim

python -m pip install --user --upgrade pynvim
python2.7 -m pip install --user --upgrade pynvim neovim
