#!/bin/bash

ln -sfv $DOTFILES/.overrides ~ || exit 1
ln -sfv $DOTFILES/.variables ~ || exit 1
ln -sfv $DOTFILES/.functions ~ || exit 1
ln -sfv $DOTFILES/.bash_profile ~ || exit 1
ln -sfv $DOTFILES/.bashrc ~ || exit 1

if [[ $SHELL = "/bin/bash" ]]; then
	echo "Reloading bash configuration"
	source ~/.bash_profile || exit 1
fi
