#!/bin/bash
set -euxo pipefail

ln -sfv $DOTFILES/.overrides ~
ln -sfv $DOTFILES/.variables ~
ln -sfv $DOTFILES/.functions ~
ln -sfv $DOTFILES/.bash_profile ~
ln -sfv $DOTFILES/.bashrc ~

if [[ $SHELL = "/bin/bash" ]]; then
	echo "Reloading bash configuration"
	source ~/.bash_profile
fi
