#!/bin/bash
set -euxo pipefail

echo "Checking for oh-my-zsh installation"
if [ ! -d "$HOME/.oh-my-zsh" ]; then
	curl -L http://install.ohmyz.sh | sh
else
	echo "Already installed"
fi

ln -sfv $DOTFILES/.zshrc ~

if command -v getent &> /dev/null
then
	CURRENT_SHELL=$(getent passwd $USER | awk -F: '{print $NF }')
else
	CURRENT_SHELL=/bin/bash
fi

if [$CURRENT_SHELL != $(which zsh) ]; then
	chsh -s $(which zsh)
else
	echo "ZSH already set as default shell"
fi
