#!/bin/bash

sudo ln -sfv $DOTFILES/.xsession ~ || exit 1

sudo sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
sudo cat /etc/sudoers | grep wheel

# xmonad
ln -sfv $DOTFILES/xmonad/xmonad.hs ~/.xmonad.hs

# lightdm
if sudo test -f "/etc/lightdm/lightdm.conf.original"; then
	echo "Original lightdm configuration already exists"
else
	echo "Creating backup of original lightdm configuration"
	sudo cp /etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf.original
fi

sudo grep 'autologin-user=\|autologin-session=\|greeter-session=' /etc/lightdm/lightdm.conf &&
sudo sed -i "s/#autologin-user=/autologin-user=$USER/g" /etc/lightdm/lightdm.conf && \
sudo sed -i "s/#autologin-session=/autologin-session=xmonad/g" /etc/lightdm/lightdm.conf && \
sudo sed -i "s/#greeter-session=example-gtk-gnome/autologin-user=lightdm-gtk-greeter/g" /etc/lightdm/lightdm.conf && \
sudo grep 'autologin-user=\|autologin-session=\|greeter-session=' /etc/lightdm/lightdm.conf

sudo systemctl enable lightdm
