#!/bin/bash
set -euxo pipefail

sudo ln -sfv $DOTFILES/.xsession ~

sudo sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers
sudo cat /etc/sudoers | grep wheel

# xmonad
if [ ! -d $HOME/.xmonad ]; then
    mkdir ~/.xmonad
fi

ln -sfv $DOTFILES/xmonad/xmonad.hs ~/.xmonad/xmonad.hs

# xmobar
ln -sfv $DOTFILES/.xmobarrc ~

# lightdm
if sudo test -f "/etc/lightdm/lightdm.conf.original"; then
	echo "Original lightdm configuration already exists"
else
	echo "Creating backup of original lightdm configuration"
	sudo cp /etc/lightdm/lightdm.conf /etc/lightdm/lightdm.conf.original
fi

sudo grep 'autologin-user=\|autologin-session=\|greeter-session=' /etc/lightdm/lightdm.conf &&
sudo sed -i "s/#autologin-user=/autologin-user=$USER/g" /etc/lightdm/lightdm.conf && \
sudo sed -i "s/#autologin-session=/autologin-session=xmonad/g" /etc/lightdm/lightdm.conf && \
sudo sed -i "s/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/g" /etc/lightdm/lightdm.conf && \
sudo grep 'autologin-user=\|autologin-session=\|greeter-session=' /etc/lightdm/lightdm.conf

sudo sed -i 's/greeter-session=lightdm-gtk-greeter/greeter-session=lightdm-webkit2-greeter/g' /etc/lightdm/lightdm.conf
sudo cp $DOTFILES/lightdm-webkit2-greeter.conf /etc/lightdm
sudo cp $DOTFILES/wallpapers/* /usr/share/backgrounds

if [ ! -f "~/.avatar.png" ]; then
    cp $DOTFILES/avatar.png ~/.face
fi

sudo systemctl enable lightdm

# dolpin file explorer

mkdir -p ~/.config/qt5ct

cp -v $DOTFILES/kdeglobals ~/.config
ln -sfv $DOTFILES/.gtkrc-2.0 ~/.config
ln -sfv $DOTFILES/baloofileinformationrc ~/.config
ln -sfv $DOTFILES/gtk-2.0 ~/.config
ln -sfv $DOTFILES/gtk-3.0 ~/.config
ln -sfv $DOTFILES/qt5ct.conf ~/.config/qt5ct
sudo cp -v $DOTFILES/org.freedesktop.UDisks2.policy /usr/share/polkit-1/actions

balooctl enable

# dunst desktop notifications

sudo ln -sfv $DOTFILES/dunst ~/.config
