#!/bin/bash
set -euxo pipefail
source "$DOTFILES/.bash_helpers"

sudo sed -i 's/#AutoEnable=false/AutoEnable=true/g' /etc/bluetooth/main.conf
sudo usermod -a -G rfkill $USER
sudo systemctl enable bluetooth
