#!/bin/bash

if [[ -d /opt/neovim ]]
then
    echo "neovim already installed, skipping."
else
    cd /opt
    wget https://github.com/neovim/neovim/releases/download/v0.4.4/nvim-linux64.tar.gz
    tar zxvf nvim-linux64.tar.gz
    mv nvim-linux64 neovim
    rm /opt/nvim-linux64.tar.gz
fi

if command -v apt &> /dev/null
then
	sudo add-apt-repository universe
	sudo apt install -y ruby xclip python2 gcc make python-pip nodejs npm php php-zip composer ctags \
			elixir pylint python-pillow yarn ripgrep

	# elixir-ls the_silver_searcher

	# python2-pip
	cd /tmp
	curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
	sudo python2 get-pip.py

	# composer 2
	php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
	php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
	php composer-setup.php
	php -r "unlink('composer-setup.php');"
	mv /tmp/composer.phar /usr/bin/composer
fi
