#!/bin/bash

DMENU=${DMENU:-dmenu}

prompt="DEVICE"
cmd_list="$(pactl list | grep "Name: alsa_output.\|Name: bluez_sink." | grep --invert-match "monitor" | sed 's/Name: //g')"
cmd="$(echo $cmd_list | sed 's/ /\n/g' | ${DMENU} -p "$prompt")"

[[ -z $cmd ]] && exit 1

paswitch "${cmd}"
